name: build-pasopa
# Import solution from Github repo
# TODO: Use PASOpa to pack the .msapp file

on:
  workflow_dispatch:

jobs:
  import-from-repo:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - uses: actions/checkout@v2
      with:
        lfs: true
        repository: microsoft/PowerApps-Language-Tooling
        path: temp/pasopa
        
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: temp/pasopa
        solution-target-folder: tools/PASOpa
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true

    
