name: build-pasopa
# Import solution from Github repo
# TODO: Use PASOpa to pack the .msapp file

on:
  workflow_dispatch:

jobs:
  import-from-repo:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - uses: actions/checkout@v2
      with:
        lfs: true
        repository: microsoft/PowerApps-Language-Tooling
        path: temp/pasopa
        
    - name: Setup .NET Core SDK 3.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r win10-x64 -p:PublishSingleFile=true --self-contained true temp/pasopa/src
    
