name: build-pasopa
# Import solution from Github repo
# TODO: Use PASOpa to pack the .msapp file

on:
  workflow_dispatch:

jobs:
  import-from-repo:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - uses: actions/checkout@v2
      with:
        lfs: true
        repository: microsoft/PowerApps-Language-Tooling
        ref: '0.2.1-preview'
        path: temp/pasopa
        
    - name: Setup .NET Core SDK 3.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x'
    - name: Display dotnet version
      run: dotnet --version
    - name: Build
      working-directory: ./temp/pasopa/src
      run: dotnet publish --output ./tools/pasopa --runtime win-x64 --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
     # run: build ci
     # shell: cmd
    #- name: Test that it works
    #  run: ./bin/Debug/PASopa/PASopa.dll
    
