name: add-tools-to-path

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: add tools to path
      run: pwd
