name: do-stuff

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: echo home
      shell: cmd
      run: cd
      
    - name: echo full path
      shell: cmd
      run: echo ${{ GITHUB_WORKSPACE }}\out\solutions\EDSTemplate\CanvasApps\new_bulbdigitalthemetemplatedemo_e7a6f_DocumentUri
      
    #- name: echo path
     # shell: cmd
     # run: echo %PATH%
      
    #- name: add to path
    #  run: echo "##[add-path]D:\a\eds-powerapps-poc\eds-powerapps-poc\tools"
      
    #- name: run pasopa
    #  shell: cmd
    #  run: which pasopa
    
    #- name: run pasopa
    #  shell: cmd
    #  run: tools\pasopa -unpack solutions\EDSTemplate\CanvasApps\new_bulbdigitalthemetemplatedemo_e7a6f_DocumentUri.msapp
    
    # - name: prepare packing
    #  shell: cmd
    #  run: tools\pasopa -pack solutions\EDSTemplate\CanvasApps\new_bulbdigitalthemetemplatedemo_e7a6f_DocumentUri.msapp solutions\EDSTemplate\CanvasApps\new_bulbdigitalthemetemplatedemo_e7a6f_DocumentUri_src
    #  
    #- name: remove .msapp dir
    #  shell: bash
    #  run: rm -rf solutions/EDSTemplate/CanvasApps/new_bulbdigitalthemetemplatedemo_e7a6f_DocumentUri
      
