name: add-tools-to-path

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: echo home
      shell: cmd
      run: cd
      
    - name: echo path
      shell: cmd
      run: echo %PATH%
      
    - name: add to path
      shell: cmd
      run: setx path "%path%;D:\a\eds-powerapps-poc\eds-powerapps-poc\tools"
      
    - name: echo path again
      shell: cmd
      run: echo %PATH%
