name: add-tools-to-path

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: echo home
      shell: cmd
      run: cd
      
    #- name: echo path
     # shell: cmd
     # run: echo %PATH%
      
    #- name: add to path
    #  run: echo "##[add-path]D:\a\eds-powerapps-poc\eds-powerapps-poc\tools"
      
    #- name: run pasopa
    #  shell: cmd
    #  run: which pasopa
    
    - name: run pasopa
      shell: cmd
      run: tools\pasopa -unpack solutions\EDSTemplate\CanvasApps\*.msapp
      
