name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes
# TODO: Use PASOpa to unpack the .msapp file

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://edsdev.crm4.dynamics.com'
        client-secret: ${{ secrets.password }}
        app-id: 'dfab4afd-0e14-48ee-997e-04e8defbcf6f'
        tenant-id: '3aa4a235-b6e2-48d5-9195-7fcf05b459b0'

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://edsdev.crm4.dynamics.com'
        client-secret: ${{ secrets.password }}
        app-id: 'dfab4afd-0e14-48ee-997e-04e8defbcf6f'
        tenant-id: '3aa4a235-b6e2-48d5-9195-7fcf05b459b0'
        solution-name: EDSTemplate
        solution-output-file: out/exported/EDSTemplate.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/EDSTemplate.zip
        solution-folder: out/solutions/EDSTemplate
        solution-type: 'Unmanaged'
        overwrite-files: true
        
    - name: seriously unpack solution
      shell: cmd
      run: >-
        tools\pasopa -unpack 
        out\solutions\EDSTemplate\CanvasApps\new_bulbdigitalthemetemplatedemo_e7a6f_DocumentUri.msapp 
        out\solutions\EDSTemplate\CanvasApps\new_bulbdigitalthemetemplatedemo_e7a6f_DocumentUri
      
    - name: remove .msapp file
      shell: cmd
      run: >-
        del
        out\solutions\EDSTemplate\CanvasApps\new_bulbdigitalthemetemplatedemo_e7a6f_DocumentUri.msapp

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/EDSTemplate
        solution-target-folder: solutions/EDSTemplate
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
