name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://edsdev.crm4.dynamics.com'
        user-name: 'EDSPowerApptemplate'
        password-secret: ${{ secrets.password }}
        app-id: 'dfab4afd-0e14-48ee-997e-04e8defbcf6f'

#    - name: export-solution action
#      uses: microsoft/powerplatform-actions/export-solution@v0
#      with:
#        environment-url: 'https://make.powerapps.com/environments/2c26a774-49a8-4666-9eae-968f48d2ad03/home'
#        user-name: 'EDSPowerApptemplate'
#        password-secret: ${{ secrets.password }}
#        solution-name: ALMLab
#        solution-output-file: out/exported/ALMLab.zip

#    - name: unpack-solution action
#      uses: microsoft/powerplatform-actions/unpack-solution@v0
#      with:
#        solution-file: out/exported/ALMLab.zip
#        solution-folder: out/solutions/ALMLab
#        solution-type: 'Unmanaged'
#        overwrite-files: true

#    - name: branch-solution, prepare it for a PullRequest
#      uses: microsoft/powerplatform-actions/branch-solution@v0
#      with:
#        solution-folder: out/solutions/ALMLab
#        solution-target-folder: solutions/ALMLab
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
#        allow-empty-commit: true
